name: async_builder
description: Improved Future and Stream builder for Flutter.
version: 1.0.0
homepage: https://github.com/PixelToast/async_snapshot

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rxdart: ^0.23.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: