name: async_builder
description: Flutter Future and Stream builder with less boilerplate and better error handling.
version: 1.1.0
homepage: https://github.com/PixelToast/async_builder

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rxdart: ">=0.20.0 <1.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: